pipeline {
   agent any
   environment {
       POSTGRES_SECRET = credentials('postgres-secret')
   }
   stages {
       stage('Checkout') {
           steps {
               checkout scm
           }
       }
       stage('Run tests') {
           steps {
               sh '''
               podman run --rm \
                 -v $WORKSPACE:/app \
                 -w /app \
                 python:3.11 \
                 bash -c "
                   pip install --upgrade pip &&
                   pip install -r requirements.txt &&
                   pytest tests -s -m parquet_data \
                     --db_host=localhost \
                     --db_port=5434 \
                     --db_name=mydatabase \
                     --db_user=$POSTGRES_SECRET_USR \
                     --db_password=$POSTGRES_SECRET_PSW \
                     --html=html_report/report.html \
                     --self-contained-html
                 "
               '''
           }
       }
       stage('Archive Test Report') {
           steps {
               archiveArtifacts artifacts: 'html_report/**', allowEmptyArchive: true
               publishHTML(target: [
                   allowMissing: false,
                   keepAll: true,
                   reportDir: 'html_report',
                   reportFiles: 'report.html',
                   reportName: 'PyTest Report_DQ-Framework'
               ])
           }
       }
   }
}