pipeline {
   agent any

   environment {
       POSTGRES_SECRET = credentials('postgres-secret')
       DB_HOST = 'localhost'
       DB_PORT = '5434'
       DB_NAME = 'mydatabase'
       PYTHONPATH = "${WORKSPACE}"
   }

   stages {

       stage('Checkout') {
           steps {
               checkout scm
           }
       }

       stage('Verify') {
           steps {
               sh '''
               python3 --version
               pip3 --version
               '''
           }
       }

       stage('Install dependencies') {
           steps {
               sh '''
               python3 -m venv venv
               . venv/bin/activate

               pip install --upgrade pip
               pip install -r "PyTest DQ Framework/requirements.txt"
               '''
           }
       }

       stage('Run tests') {
           steps {
               sh '''
               . venv/bin/activate

               pytest "PyTest DQ Framework/tests" -s -m parquet_data \
                 --db_host=$DB_HOST \
                 --db_port=$DB_PORT \
                 --db_name=$DB_NAME \
                 --db_user=$POSTGRES_SECRET_USR \
                 --db_password=$POSTGRES_SECRET_PSW \
                 --html="PyTest DQ Framework/html_report/report.html" \
                 --self-contained-html \
                 --junitxml="PyTest DQ Framework/report.xml"
               '''
           }
       }

       stage('Archive') {
           steps {
               archiveArtifacts artifacts: 'PyTest DQ Framework/html_report/**'
               junit 'PyTest DQ Framework/report.xml'
           }
       }
   }
}